apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  labels:
    app: test
spec:
  replicas: 30
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: traefik
        image: traefik
        ports:
        - containerPort: 80
