name: Build jar

on:
   push:
      branches:
         - master
   pull_request:
      branches:
         - master

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - name: Set up JDK 1.8
           uses: actions/setup-java@v1
           with:
              java-version: 1.8
         - name: Grant execute permission for gradlew
           run: chmod +x gradlew
         - name: Build with Gradle
           run: ./gradlew shadowJar
         - name: Set environment variables
           run: |
             export ARCHIVE_NAME=$(./gradlew getArchiveName --quiet)
             echo "::set-env name=ARCHIVE_NAME::$ARCHIVE_NAME"
         - name: Upload jar
           uses: actions/upload-artifact@v2
           with:
             name: shadow-jar
             path: 'build/libs/${{ env.ARCHIVE_NAME }}.jar'